class RestaurantTable {
  final int id;
  final String tableNumber;
  final String status;

  RestaurantTable({required this.id, required this.tableNumber, required this.status});

  factory RestaurantTable.fromJson(Map<String, dynamic> json) {
    return RestaurantTable(
      id: json['id'] as int,
      tableNumber: json['table_number'] as String,
      status: json['status'] as String,
    );
  }

  Map<String, dynamic> toJson() => {
    'table_number': tableNumber,
    'status': status,
  }; // ID is auto-generated by the database
}